// ComCalculator.idl : IDL source for ComCalculator
//

// This file will be processed by the MIDL tool to
// produce the type library (ComCalculator.tlb) and marshalling code.

import "oaidl.idl";
import "ocidl.idl";

// Forward declarations
interface ICalculatorApplication;
interface ICalculatorPlugin;

// Interfaces
[
	object,
	uuid(8388A2A1-AEFF-4F07-97B3-4F67A4E3F450),
	dual,
	nonextensible,
	pointer_default(unique)
]
interface ICalculatorApplication : IDispatch{
	[id(1)] HRESULT GetPlugin([in] BSTR progId, [out, retval] ICalculatorPlugin** result);
	[propget, id(2)] HRESULT Name([out, retval] BSTR* pVal);
	[id(3)] HRESULT GetDomainOfManagedHelperInDefaultDomain([out,retval] BSTR* result);
	[id(4)] HRESULT GetDomainOfManagedHelperInOtherDomain([out,retval] BSTR* result);
};
[
	object,
	uuid(48A0E2FF-D8C8-4F4E-8389-0FD54E3BDC9A),
	dual,
	nonextensible,
	pointer_default(unique)
]
interface ICalculatorPlugin : IDispatch{
	[id(1)] HRESULT Initialize([in] ICalculatorApplication* application);
	[id(2), helpstring("Adds two numbers")] HRESULT Add([in] int left, [in] int right, [out,retval] int* result);
};
[
	uuid(C4456541-5B90-4051-88B5-5EC57A857ADF),
	version(1.0),
]

// Library
library ComCalculatorLib
{
	importlib("stdole2.tlb");
	[
		uuid(31A18EE5-90F8-4C35-8861-67A2A2419036)		
	]
	coclass CalculatorPlugin
	{
		[default] interface ICalculatorPlugin;
	};
	[
		uuid(66AEC723-FC7D-4C9A-BD8C-1AA7F7568AB9)		
	]
	coclass CalculatorApplication
	{
		[default] interface ICalculatorApplication;
	};
};

